//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTS.IO {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class HWSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HWSettings defaultInstance = ((HWSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HWSettings())));
        
        public static HWSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double XYDistance {
            get {
                return ((double)(this["XYDistance"]));
            }
            set {
                this["XYDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double YZDistance {
            get {
                return ((double)(this["YZDistance"]));
            }
            set {
                this["YZDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double XZDistance {
            get {
                return ((double)(this["XZDistance"]));
            }
            set {
                this["XZDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,-1")]
        public global::System.Windows.Media.Media3D.Vector3D ZeroPlaneNormal {
            get {
                return ((global::System.Windows.Media.Media3D.Vector3D)(this["ZeroPlaneNormal"]));
            }
            set {
                this["ZeroPlaneNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfChannelSetting xmlns:xsi=\"http:/" +
            "/www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema" +
            "\">\r\n  <ChannelSetting>\r\n    <Id>DistanceX</Id>\r\n    <Name>Distance Sensor X</Nam" +
            "e>\r\n    <Description>Calibrator X that is measuring distance from mirror glass</" +
            "Description>\r\n    <RawLow>0</RawLow>\r\n    <RawHigh>4095</RawHigh>\r\n    <RealLow>" +
            "0</RealLow>\r\n    <RealHigh>100</RealHigh>\r\n  </ChannelSetting>\r\n  <ChannelSettin" +
            "g>\r\n    <Id>DistanceY</Id>\r\n    <Name>Distance Sensor Y</Name>\r\n    <Description" +
            ">Calibrator Y that is measuring distance from mirror glass</Description>\r\n    <R" +
            "awLow>0</RawLow>\r\n    <RawHigh>4095</RawHigh>\r\n    <RealLow>0</RealLow>\r\n    <Re" +
            "alHigh>100</RealHigh>\r\n  </ChannelSetting>\r\n  <ChannelSetting>\r\n    <Id>Distance" +
            "Z</Id>\r\n    <Name>Distance Sensor Z</Name>\r\n    <Description>Calibrator Z that i" +
            "s measuring distance from mirror glass</Description>\r\n    <RawLow>0</RawLow>\r\n  " +
            "  <RawHigh>4095</RawHigh>\r\n    <RealLow>0</RealLow>\r\n    <RealHigh>100</RealHigh" +
            ">\r\n  </ChannelSetting>\r\n  <ChannelSetting>\r\n    <Id>PowerfoldCurrent</Id>\r\n    <" +
            "Name>Powerfold Current</Name>\r\n    <Description>Amphermeter that is measuring cu" +
            "rrent of powerfold actuator</Description>\r\n    <RawLow>0</RawLow>\r\n    <RawHigh>" +
            "4095</RawHigh>\r\n    <RealLow>0</RealLow>\r\n    <RealHigh>4000</RealHigh>\r\n  </Cha" +
            "nnelSetting>\r\n  <ChannelSetting>\r\n    <Id>HeatingFoilCurrent</Id>\r\n    <Name>Hea" +
            "ting Foil Current</Name>\r\n    <Description>Amphermeter that is measuring current" +
            " in heating foil</Description>\r\n    <RawLow>0</RawLow>\r\n    <RawHigh>4095</RawHi" +
            "gh>\r\n    <RealLow>0</RealLow>\r\n    <RealHigh>4000</RealHigh>\r\n  </ChannelSetting" +
            ">\r\n  <ChannelSetting>\r\n    <Id>VerticalActuatorCurrent</Id>\r\n    <Name>Vertical " +
            "ActuatorCurrent</Name>\r\n    <Description>Amphermeter that is measuring current o" +
            "f actuator moveing mirror glass vertically</Description>\r\n    <RawLow>0</RawLow>" +
            "\r\n    <RawHigh>4095</RawHigh>\r\n    <RealLow>0</RealLow>\r\n    <RealHigh>2000</Rea" +
            "lHigh>\r\n  </ChannelSetting>\r\n  <ChannelSetting>\r\n    <Id>HorizontalActuatorCurre" +
            "nt</Id>\r\n    <Name>Horizontal Actuator Current</Name>\r\n    <Description>Ampherme" +
            "ter that is measuring current of actuator moveing mirror glass horizontaly</Desc" +
            "ription>\r\n    <RawLow>0</RawLow>\r\n    <RawHigh>4095</RawHigh>\r\n    <RealLow>0</R" +
            "ealLow>\r\n    <RealHigh>2000</RealHigh>\r\n  </ChannelSetting>\r\n  <ChannelSetting>\r" +
            "\n    <Id>DirectionLightCurrent</Id>\r\n    <Name>Direction Light Current</Name>\r\n " +
            "   <Description>Amphermeter that is measuring direction light current</Descripti" +
            "on>\r\n    <RawLow>0</RawLow>\r\n    <RawHigh>4095</RawHigh>\r\n    <RealLow>0</RealLo" +
            "w>\r\n    <RealHigh>2000</RealHigh>\r\n  </ChannelSetting>\r\n  <ChannelSetting>\r\n    " +
            "<Id>PowerSupplyVoltage1</Id>\r\n    <Name>Power Supply Voltage 1</Name>\r\n    <Desc" +
            "ription>Voltmeter that is meausring voltage of power supply 1</Description>\r\n   " +
            " <RawLow>0</RawLow>\r\n    <RawHigh>4095</RawHigh>\r\n    <RealLow>0</RealLow>\r\n    " +
            "<RealHigh>10</RealHigh>\r\n  </ChannelSetting>\r\n  <ChannelSetting>\r\n    <Id>PowerS" +
            "upplyVoltage2</Id>\r\n    <Name>Power Supply Voltage 2</Name>\r\n    <Description>Vo" +
            "ltmeter that is meausring voltage of power supply 2</Description>\r\n    <RawLow>0" +
            "</RawLow>\r\n    <RawHigh>4095</RawHigh>\r\n    <RealLow>0</RealLow>\r\n    <RealHigh>" +
            "10</RealHigh>\r\n  </ChannelSetting>\r\n</ArrayOfChannelSetting>")]
        public global::MTS.IO.ChannelSettings ChannelSettings {
            get {
                return ((global::MTS.IO.ChannelSettings)(this["ChannelSettings"]));
            }
            set {
                this["ChannelSettings"] = value;
            }
        }
    }
}
