//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTS.IO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTS.IO.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} address on channel {1} not found.
        /// </summary>
        internal static string AddrNotFoundMsg {
            get {
                return ResourceManager.GetString("AddrNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} address can not be parsed from xml format.
        /// </summary>
        internal static string AddrParsingFailedMsg {
            get {
                return ResourceManager.GetString("AddrParsingFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0} could not be found.
        /// </summary>
        internal static string ChannelNotFoundMsg {
            get {
                return ResourceManager.GetString("ChannelNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} channel {1} could not be found.
        /// </summary>
        internal static string ChannelOfTypeNotFoundMsg {
            get {
                return ResourceManager.GetString("ChannelOfTypeNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the module could not be established.
        /// </summary>
        internal static string ConnectionFailedMsg {
            get {
                return ResourceManager.GetString("ConnectionFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index group: {0}, Index offset: {1}.
        /// </summary>
        internal static string EtherCATAddrStr {
            get {
                return ResourceManager.GetString("EtherCATAddrStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel in/out type {0} is uknown.
        /// </summary>
        internal static string UnkownChannelIOTypeMsg {
            get {
                return ResourceManager.GetString("UnkownChannelIOTypeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable handle of {0} address ({1}) could not be found.
        /// </summary>
        internal static string VarNotFoundMsg {
            get {
                return ResourceManager.GetString("VarNotFoundMsg", resourceCulture);
            }
        }
    }
}
