//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MTS.Data
{
    public partial class DbParamResult
    {
        public string Name { get; set; }
        public string Value { get; set; }
        public string OutputValue { get; set; }
        public int Id { get; set; }
        public byte ValueType { get; set; }
        public string Unit { get; set; }
        public string TestName { get; set; }
    }
    
}
