//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MTS.Data
{
    public partial class Test
    {
        public Test()
        {
            this.TestOutputs = new HashSet<TestOutput>();
            this.TestParams = new HashSet<TestParam>();
            this.TestShifts = new HashSet<TestShift>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TestOutput> TestOutputs { get; set; }
        public virtual ICollection<TestParam> TestParams { get; set; }
        public virtual ICollection<TestShift> TestShifts { get; set; }
    }
    
}
