//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MTS.Data
{
    public partial class TestRate
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Completed { get; set; }
        public Nullable<int> Failed { get; set; }
        public Nullable<int> Aborted { get; set; }
        public Nullable<System.TimeSpan> TotalTime { get; set; }
    }
    
}
