//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MTS.Data
{
    public partial class ShiftResult
    {
        public int Id { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Finish { get; set; }
        public int MirrorId { get; set; }
        public int OperatorId { get; set; }
        public Nullable<int> TotalSequences { get; set; }
        public Nullable<int> CompletedSequences { get; set; }
        public Nullable<int> FailedSequences { get; set; }
        public Nullable<int> AbortedSequences { get; set; }
        public Nullable<int> TotalTests { get; set; }
        public Nullable<int> CompletedTests { get; set; }
        public Nullable<int> FailedTests { get; set; }
        public Nullable<int> AbortedTests { get; set; }
        public string Mirror { get; set; }
        public string Operator { get; set; }
    }
    
}
