//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MTS.Data
{
    public partial class ShiftResult
    {
        public System.DateTime Start { get; set; }
        public System.DateTime Finish { get; set; }
        public string Mirror { get; set; }
        public string Operator { get; set; }
        public Nullable<int> TotalTests { get; set; }
        public int Completed { get; set; }
        public int Failed { get; set; }
        public int Aborted { get; set; }
    }
    
}
