//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MTS.Data
{
    public partial class Supplier
    {
        public Supplier()
        {
            this.Mirrors = new HashSet<Mirror>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Zip { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<Mirror> Mirrors { get; set; }
    }
    
}
