//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MTS.Data
{
    public partial class TestOutput
    {
        public TestOutput()
        {
            this.ParamOutputs = new HashSet<ParamOutput>();
        }
    
        public int Id { get; set; }
        public byte Result { get; set; }
        public int ShiftId { get; set; }
    
        public virtual ICollection<ParamOutput> ParamOutputs { get; set; }
        public virtual Shift Shift { get; set; }
    }
    
}
