//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class HWSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HWSettings defaultInstance = ((HWSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HWSettings())));
        
        public static HWSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.Media3D.Vector3D ZeroPlaneNormal {
            get {
                return ((global::System.Windows.Media.Media3D.Vector3D)(this["ZeroPlaneNormal"]));
            }
            set {
                this["ZeroPlaneNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0")]
        public global::System.Windows.Media.Media3D.Point3D SondeYPosition {
            get {
                return ((global::System.Windows.Media.Media3D.Point3D)(this["SondeYPosition"]));
            }
            set {
                this["SondeYPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,94.4,0")]
        public global::System.Windows.Media.Media3D.Point3D SondeZPosition {
            get {
                return ((global::System.Windows.Media.Media3D.Point3D)(this["SondeZPosition"]));
            }
            set {
                this["SondeZPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("58.8,94.4,0")]
        public global::System.Windows.Media.Media3D.Point3D SondeXPosition {
            get {
                return ((global::System.Windows.Media.Media3D.Point3D)(this["SondeXPosition"]));
            }
            set {
                this["SondeXPosition"] = value;
            }
        }
        
        /// <summary>
        /// Distance of X and Y sondes. Sonds are measuring distance between them and mirror glass
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Distance of X and Y sondes. Sonds are measuring distance between them and mirror " +
            "glass")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double XYDistance {
            get {
                return ((double)(this["XYDistance"]));
            }
            set {
                this["XYDistance"] = value;
            }
        }
        
        /// <summary>
        /// Distance of Y and Z sondes. Sonds are measuring distance between them and mirror glass
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Distance of Y and Z sondes. Sonds are measuring distance between them and mirror " +
            "glass")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double YZDistance {
            get {
                return ((double)(this["YZDistance"]));
            }
            set {
                this["YZDistance"] = value;
            }
        }
        
        /// <summary>
        /// Distance of X and Z sondes. Sonds are measuring distance between them and mirror glass
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Distance of X and Z sondes. Sonds are measuring distance between them and mirror " +
            "glass")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double XZDistance {
            get {
                return ((double)(this["XZDistance"]));
            }
            set {
                this["XZDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::MTS.Admin.ChannelSettingsCollection ChannelsSettinngs {
            get {
                return ((global::MTS.Admin.ChannelSettingsCollection)(this["ChannelsSettinngs"]));
            }
            set {
                this["ChannelsSettinngs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::MTS.Admin.ChannelSetting Setting {
            get {
                return ((global::MTS.Admin.ChannelSetting)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
