//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTS.Tester {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTS.Tester.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string AbortedMsg {
            get {
                return ResourceManager.GetString("AbortedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing connection ....
        /// </summary>
        internal static string ClosingConnectionMsg {
            get {
                return ResourceManager.GetString("ClosingConnectionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating communication channels ....
        /// </summary>
        internal static string CreatingChannelsMsg {
            get {
                return ResourceManager.GetString("CreatingChannelsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string FailedMsg {
            get {
                return ResourceManager.GetString("FailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror failed.
        /// </summary>
        internal static string MirrorFailedMsg {
            get {
                return ResourceManager.GetString("MirrorFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror passed.
        /// </summary>
        internal static string MirrorPassedMsg {
            get {
                return ResourceManager.GetString("MirrorPassedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKMsg {
            get {
                return ResourceManager.GetString("OKMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters loaded from file {0}.
        /// </summary>
        internal static string ParamLoadedMsg {
            get {
                return ResourceManager.GetString("ParamLoadedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string PassedMsg {
            get {
                return ResourceManager.GetString("PassedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result: {0}.
        /// </summary>
        internal static string ResultMsg {
            get {
                return ResourceManager.GetString("ResultMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving results do database ... .
        /// </summary>
        internal static string SavingDataMsg {
            get {
                return ResourceManager.GetString("SavingDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test sequence {0} finished.
        /// </summary>
        internal static string SequenceFinishedMsg {
            get {
                return ResourceManager.GetString("SequenceFinishedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test sequence {0} started.
        /// </summary>
        internal static string SequenceStartedMsg {
            get {
                return ResourceManager.GetString("SequenceStartedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift aborted!.
        /// </summary>
        internal static string ShiftAbortedMsg {
            get {
                return ResourceManager.GetString("ShiftAbortedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift finished!.
        /// </summary>
        internal static string ShiftFinishedMsg {
            get {
                return ResourceManager.GetString("ShiftFinishedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting shift failed.
        /// </summary>
        internal static string StartingShiftFailedMsg {
            get {
                return ResourceManager.GetString("StartingShiftFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting shift ... .
        /// </summary>
        internal static string StartingShiftMsg {
            get {
                return ResourceManager.GetString("StartingShiftMsg", resourceCulture);
            }
        }
    }
}
